export const queryKeys = {
  tenant: ["tenant.current"] as const,
  teacherCalendar: ["teacher.calendar"] as const,
  teacherCurrentLesson: ["teacher.currentLesson"] as const,
  teacherStudents: ["teacher.students"] as const,
  teacherObservations: ["teacher.observations"] as const,
  teacherAnnouncements: ["teacher.announcements"] as const,
  attendanceSession: (lessonId: string) => ["teacher.attendanceSession", lessonId] as const,
  guardianStudents: ["guardian.children"] as const,
  guardianSchedule: (studentId: string) => ["guardian.childSchedule", studentId] as const,
  guardianAttendance: (studentId: string) => ["guardian.childAttendance", studentId] as const,
  guardianBilling: (studentId: string) => ["guardian.billing", studentId] as const,
  guardianService: (studentId: string) => ["guardian.service", studentId] as const,
  guardianServiceTrip: (studentId: string) => ["guardian.serviceTrip", studentId] as const,
  driverSession: ["driver.session"] as const,
  activeServiceTrips: ["service.activeTrips"] as const,
  guardianLife: (studentId: string) => ["guardian.life", studentId] as const,
  guidanceObservations: ["guidance.observations"] as const,
  guidanceStudents: ["guidance.students"] as const,
  guidanceNotes: ["guidance.notes"] as const,
  guidanceSupportPlans: ["guidance.supportPlans"] as const,
  guidanceRiskTrackings: ["guidance.riskTrackings"] as const,
  guidanceCases: ["guidance.cases"] as const,
  guidanceCase: (caseId: string) => ["guidance.case", caseId] as const,
  guidanceCaseEvents: (caseId: string) => ["guidance.caseEvents", caseId] as const,
  guidanceCaseTimeline: (caseId: string) => ["guidance.caseTimeline", caseId] as const,
  guidanceCaseStats: ["guidance.caseStats"] as const,
  guidanceStudentCaseSummary: (studentId: string) => ["guidance.studentCaseSummary", studentId] as const,
  principalSummary: ["principal.summary"] as const,
  principalRoster: ["principal.roster"] as const,
  billingDashboard: ["billing.dashboard"] as const,
  billingOverdueReport: ["billing.overdueReport"] as const,
  billingInstallments: (status?: string) => ["billing.installments", status ?? "all"] as const,
  billingStudentAccount: (studentId: string) => ["billing.studentAccount", studentId] as const,
  serviceRoutes: ["service.routes"] as const,
  serviceVehicles: ["service.vehicles"] as const,
  serviceStaff: ["service.staff"] as const,
  lifeMeals: ["life.meals"] as const,
  studySessions: ["life.studySessions"] as const,
  clubs: ["life.clubs"] as const,
  principalAttendanceToday: (date: string) => ["principal.attendanceToday", date] as const,
  principalClassAttendance: (classId: string, date: string) => ["principal.classAttendance", classId, date] as const,
  announcements: (mode: string, manage = false) => ["announcements.list", mode, manage] as const,
  notifications: (mode: string) => ["notifications.list", mode] as const,
  supportTickets: ["support.tickets"] as const,
  profile: ["profile.me"] as const,
  notificationPreferences: ["profile.notificationPreferences"] as const,
  principalTeachers: ["principal.teachers"] as const,
  studentImportJobs: ["principal.studentImportJobs"] as const,
  studentImportJob: (jobId: string) => ["principal.studentImportJob", jobId] as const,
  schedule: ["schedule.current"] as const,
  scheduleById: (id: string) => ["schedule.byId", id] as const,
  schedulingRequirements: ["scheduling.requirements"] as const,
  teacherAvailabilities: ["scheduling.availabilities"] as const,
  scheduleConflicts: (scheduleId: string) => ["schedule.conflicts", scheduleId] as const,
  scheduleChangeLog: (scheduleId: string) => ["schedule.changeLog", scheduleId] as const,
  academicAssessments: ["academic.assessments"] as const,
  academicAssessmentResults: (assessmentId: string) => ["academic.assessmentResults", assessmentId] as const,
  studentAcademicSummary: (studentId: string) => ["academic.studentSummary", studentId] as const,
  classAcademicSummary: (classId: string) => ["academic.classSummary", classId] as const,
  guardianAcademicReport: (studentId: string) => ["guardian.academicReport", studentId] as const,
  aiCapabilities: ["ai.capabilities"] as const
};
