export const queryKeys = {
  tenant: ["tenant.current"] as const,
  teacherCalendar: ["teacher.calendar"] as const,
  teacherCurrentLesson: ["teacher.currentLesson"] as const,
  teacherStudents: ["teacher.students"] as const,
  teacherObservations: ["teacher.observations"] as const,
  teacherAnnouncements: ["teacher.announcements"] as const,
  attendanceSession: (lessonId: string) => ["teacher.attendanceSession", lessonId] as const,
  guardianStudents: ["guardian.children"] as const,
  guardianSchedule: (studentId: string) => ["guardian.childSchedule", studentId] as const,
  guardianAttendance: (studentId: string) => ["guardian.childAttendance", studentId] as const,
  guidanceObservations: ["guidance.observations"] as const,
  guidanceStudents: ["guidance.students"] as const,
  guidanceNotes: ["guidance.notes"] as const,
  guidanceSupportPlans: ["guidance.supportPlans"] as const,
  guidanceRiskTrackings: ["guidance.riskTrackings"] as const,
  principalSummary: ["principal.summary"] as const,
  principalRoster: ["principal.roster"] as const,
  principalAttendanceToday: (date: string) => ["principal.attendanceToday", date] as const,
  principalClassAttendance: (classId: string, date: string) => ["principal.classAttendance", classId, date] as const,
  announcements: (mode: string) => ["announcements.list", mode] as const,
  notifications: (mode: string) => ["notifications.list", mode] as const,
  supportTickets: ["support.tickets"] as const,
  profile: ["profile.me"] as const,
  principalTeachers: ["principal.teachers"] as const,
  schedule: ["schedule.current"] as const,
  scheduleById: (id: string) => ["schedule.byId", id] as const,
  schedulingRequirements: ["scheduling.requirements"] as const,
  teacherAvailabilities: ["scheduling.availabilities"] as const,
  aiCapabilities: ["ai.capabilities"] as const
};
